# Generated by Django 5.1.2 on 2024-12-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("handle_questions", "0003_alter_questionresponsemapping_client"),
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="developerprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="ClientProfile",
        ),
        migrations.DeleteModel(
            name="DeveloperProfile",
        ),
    ]
