# Generated by Django 5.1.2 on 2025-01-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_in", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Applicationfeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_type", models.TextField()),
                ("feature_description", models.TextField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "applicationfeatures",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Budgetoverview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "budget_allocated",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "budget_spent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "budgetoverview",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unavailable_start", models.DateField()),
                ("unavailable_end", models.DateField()),
            ],
            options={
                "db_table": "calendar",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("message_type", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("is_read", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "chat",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Collaborationnotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("communication_style", models.TextField()),
                ("preferred_approach", models.TextField(blank=True, null=True)),
                ("recurring_meetings", models.BooleanField(blank=True, null=True)),
                ("additional_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "collaborationnotes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Communicationpreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preferred_method", models.TextField()),
                ("expected_response_time", models.TextField()),
                ("detailed_notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "communicationpreferences",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Developerpreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preferred_developers", models.JSONField(blank=True, null=True)),
                ("interview_required", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "developerpreferences",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Developerrating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.FloatField()),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "developerrating",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feedback_text", models.TextField()),
                ("feedback_type", models.TextField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "feedback",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "notifications",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.TextField(blank=True, null=True)),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                ("payment_method", models.TextField()),
            ],
            options={
                "db_table": "payments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Profileprojects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.TextField()),
                ("specialization", models.TextField()),
                ("technologies", models.JSONField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "profileprojects",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Projectbudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("budget_range", models.TextField()),
                (
                    "budget_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "projectbudget",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Projectdesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color_palette", models.JSONField(blank=True, null=True)),
                ("layout_preferences", models.TextField(blank=True, null=True)),
                ("additional_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "projectdesign",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Projectobjectives",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objective_type", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "projectobjectives",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Projectreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference_link", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "projectreferences",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("technologies", models.JSONField(blank=True, null=True)),
                ("team_members", models.JSONField(blank=True, null=True)),
                ("duration", models.TextField(blank=True, null=True)),
                ("users", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "projects",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("question_type", models.TextField(blank=True, null=True)),
                ("options", models.JSONField(blank=True, null=True)),
                ("step", models.IntegerField()),
                ("category", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "questionnaire",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Questionresponsemapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response", models.TextField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "questionresponsemapping",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Quickactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_type", models.TextField()),
                ("action_name", models.TextField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "quickactions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Rechargecodes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField()),
                ("status", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "rechargecodes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Registrationdetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("developer", models.BooleanField(blank=True, null=True)),
                ("registration_source", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "registrationdetails",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Sidebarpreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active_tab", models.TextField(blank=True, null=True)),
                ("customization", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "sidebarpreferences",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_type", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, null=True)),
                ("transaction_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "transactions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("last_recharge", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "wallet",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="clientprofile",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="developerprofile",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"managed": False},
        ),
    ]
