# Generated by Django 5.1.2 on 2025-01-01 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("log_in", "0002_applicationfeatures_budgetoverview_calendar_chat_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="clientprofile",
            table="clientprofile",
        ),
        migrations.AlterModelTable(
            name="developerprofile",
            table="developerprofile",
        ),
        migrations.AlterModelTable(
            name="user",
            table="User",
        ),
    ]
