# Generated by Django 5.1.2 on 2025-01-01 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("log_in", "0003_alter_clientprofile_table_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"managed": True},
        ),
    ]
