# Generated by Django 5.1.2 on 2025-01-01 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("log_in", "0004_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"managed": False},
        ),
    ]
