# Generated by Django 5.1.2 on 2025-01-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_in", "0005_alter_user_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Previousprojectdev",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.TextField()),
                ("dev_speciality", models.TextField()),
            ],
            options={
                "db_table": "PreviousProjectDev",
                "managed": False,
            },
        ),
    ]
