# Generated by Django 5.1.2 on 2025-01-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("log_in", "0006_previousprojectdev"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="previousprojectdev",
            table="previousprojectdev",
        ),
    ]
