# Generated by Django 5.1.2 on 2025-01-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("log_in", "0007_alter_previousprojectdev_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="developerprofile",
            options={"managed": True},
        ),
    ]
