# Generated by Django 5.1.2 on 2025-01-12 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_in", "0008_alter_developerprofile_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"managed": True},
        ),
        migrations.AddField(
            model_name="developerprofile",
            name="accomplishments",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="developerprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="developerprofile",
            name="profile_picture",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="developerprofile",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="developerprofile",
            name="skills",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="developerprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
