# Generated by Django 5.1.2 on 2024-12-22 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("handle_questions", "0001_initial"),
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionresponsemapping",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="registration.clientprofile",
            ),
        ),
        migrations.DeleteModel(
            name="ClientProfile",
        ),
    ]
