# Generated by Django 5.1.2 on 2024-12-22 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("handle_questions", "0002_alter_questionresponsemapping_client_and_more"),
        ("log_in", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionresponsemapping",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="log_in.clientprofile",
            ),
        ),
    ]
