# Generated by Django 5.1.2 on 2024-12-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("handle_questions", "0003_alter_questionresponsemapping_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="allow_other",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="questionresponsemapping",
            name="other_response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "Multiple Choice"),
                    ("text", "Text"),
                    ("rating", "Rating"),
                    ("boolean", "Boolean"),
                    ("color_picker", "Color_picker"),
                    ("layout_selector", "Layout_selector"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
