# Generated by Django 5.1.2 on 2025-01-01 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("handle_questions", "0004_questionnaire_allow_other_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionresponsemapping",
            name="question",
        ),
        migrations.RemoveField(
            model_name="questionresponsemapping",
            name="client",
        ),
        migrations.DeleteModel(
            name="Questionnaire",
        ),
        migrations.DeleteModel(
            name="QuestionResponseMapping",
        ),
    ]
